### ISSUE TITLE
unable to run dx -t

### ISSUE THREAD

**Issue by andrei-panov** [linux-china/dx#5]
Hi,
I followed the installation process but was unable to run dx -t with `dx`.
Here the error:
```
/dx$ dx -t
error: Uncaught (in promise) TypeError: TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:100:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
        // @ts-expect-error
        ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:105:9

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:116:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:200:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:225:5

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
        // @ts-expect-error
        ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:391:9

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
      // @ts-expect-error
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:424:7

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
          // @ts-expect-error
          ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:446:11

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
          // @ts-expect-error
          ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:451:11

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:646:5

TS2578 [ERROR]: Unused '@ts-expect-error' directive.
    // @ts-expect-error
    ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.105.0/node/events.ts:667:5

TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
  signals: Deno.Signal,
                ~~~~~~
    at https://deno.land/std@0.105.0/node/os.ts:247:17

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19

Found 12 errors.
```

some details
```
/dx$ dx -v
0.1.0
/dx$ deno --version
deno 1.14.1 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.15
typescript 4.4.2
```

IMPORTANT? it was executed under MS Windows WSL2.

Thank you for your work.
Best,
Andrey.

**Comment by andrei-panov** [comment]
```
~/.deno/bin$ cat dx
#!/bin/sh
# generated by deno install
exec deno run --allow-read --allow-write --allow-net --allow-env --allow-run --allow-ffi --allow-hrtime --quiet --unstable 'https://denopkg.com/linux-china/dx/cli.ts' "$@"
```

**Comment by linux-china** [comment]
it's my fault. Could you add `--no-check` option for dx?

**Comment by andrei-panov** [comment]
Thank you! It's working now.
Just to let you know. I found your project while I was installing the Deno plugin in IDEA and found your plugin just next to it.
